export const landingPageKeywords = {
  homepage: [
    "SAP Consulting Company",
    "SAP Consulting Services",
    "Enterprise Digital Transformation",
    "ERP Consulting Company",
    "AI Automation Company",
    "Business Automation Solutions",
    "Enterprise Software Company",
    "IT Consulting Company",
    "Software Development Company",
    "SAP Implementation Partner",
    "Digital Transformation Services",
  ],
  blog: [
    "Digital Transformation Blog",
    "SAP Blog",
    "AI Blog",
    "Enterprise Technology Blog",
    "Digital Marketing Blog",
    "SEO Blog",
    "WhatsApp Automation Blog",
    "ERP Blog",
    "AI Search Optimization",
    "Business Automation Blog",
    "Technology Trends",
  ],
  services: [
    "Enterprise Technology Services",
    "SAP Services",
    "AI Solutions",
    "Enterprise Software Development",
    "Business Automation",
    "Digital Marketing Services",
    "Custom Software Development",
    "WhatsApp Automation",
    "IT Consulting Services",
    "Cloud Solutions",
    "Cyber Security Services",
  ],
  enterpriseSoftware: [
    "Enterprise Software Development Company",
    "Enterprise Software Development",
    "Custom Software Development",
    "SaaS Development",
    "ERP Software Development",
    "CRM Development",
    "Enterprise Application Development",
    "Workflow Automation Software",
    "AI Software Development",
    "Cloud Software Development",
    "Business Software Solutions",
  ],
  about: [
    "Technology Consulting Company",
    "Digital Transformation Company",
    "SAP Consulting Company",
    "Enterprise Solutions Provider",
    "AI Automation Company",
    "Software Development Company",
    "Business Technology Partner",
    "IT Consulting Company",
    "Enterprise Software Company",
    "Innovation Partner",
    "SoftClinch Chennai",
  ],
  sapConsulting: [
    "SAP Consulting Services",
    "SAP Implementation",
    "SAP S/4HANA Consulting",
    "SAP Migration",
    "SAP Rollout Services",
    "SAP AMS",
    "SAP Support Services",
    "ERP Consulting Services",
    "SAP Business Process Consulting",
    "SAP Consultant Chennai",
    "SAP Partner India",
  ],
  customApplicationDevelopment: [
    "Custom Application Development Company",
    "Custom Software Development",
    "Enterprise Application Development",
    "Web Application Development",
    "Mobile Application Development",
    "SaaS Application Development",
    "API Integration Services",
    "CRM Development",
    "ERP Integration",
    "Cloud Application Development",
    "Software Development Company",
  ],
  digitalMarketing: [
    "Digital Marketing Company",
    "SEO Services",
    "Google Ads Agency",
    "Performance Marketing",
    "Lead Generation Services",
    "Social Media Marketing",
    "Content Marketing",
    "AI SEO",
    "GEO Services",
    "AEO Services",
    "Conversion Rate Optimization",
  ],
  contact: [
    "Contact SoftClinch",
    "Contact SAP Consultant",
    "Request Consultation",
    "Book Demo",
    "Get Quote",
    "Digital Marketing Company Chennai",
    "SAP Consulting Chennai",
    "Enterprise Technology Partner",
    "AI Automation Company",
    "Software Development Company",
    "Business Consultation",
  ],
  softClinchAi: [
    "AI Automation Company",
    "AI Solutions",
    "Artificial Intelligence Company",
    "Business AI Solutions",
    "AI Chatbot Development",
    "AI Consulting Services",
    "Enterprise AI Solutions",
    "Intelligent Automation",
    "AI Integration Services",
    "Generative AI Development",
    "AI Software Company",
  ],
  inaiwazhiWhatsAppAutomation: [
    "WhatsApp Business API",
    "WhatsApp Automation",
    "WhatsApp Chatbot",
    "Bulk WhatsApp Messaging",
    "WhatsApp CRM Integration",
    "WhatsApp Marketing Software",
    "WhatsApp API Provider",
    "AI WhatsApp Chatbot",
    "WhatsApp Campaign Software",
    "Enterprise WhatsApp Solution",
    "WhatsApp Business Platform",
  ],
  commerceEnablement: [
    "Ecommerce Development Company",
    "Ecommerce Website Development",
    "Ecommerce Solutions",
    "Shopify Development",
    "WooCommerce Development",
    "Ecommerce Automation",
    "Ecommerce SEO",
    "Conversion Rate Optimization",
    "Online Store Development",
    "Ecommerce Growth Solutions",
    "Commerce Enablement Platform",
  ],
  aiPoweredBusinessSystems: [
    "AI Business Automation",
    "AI Workflow Automation",
    "Business Process Automation",
    "Enterprise AI Solutions",
    "Intelligent Business Systems",
    "AI Integration",
    "Workflow Automation Software",
    "AI Process Automation",
    "AI Software Development",
    "Enterprise Automation Solutions",
    "AI Consulting",
  ],
  sapAmsSupport: [
    "SAP AMS Services",
    "SAP Application Management Services",
    "SAP Support Services",
    "SAP Maintenance Services",
    "SAP Functional Support",
    "SAP Technical Support",
    "SAP Managed Services",
    "SAP Incident Management",
    "SAP Performance Optimization",
    "SAP Change Management",
    "SAP AMS Consultant",
  ],
} as const;

export const landingPageSeo = {
  homepage: {
    title: "SAP Consulting Company | AI & Digital Transformation | SoftClinch",
    description:
      "SoftClinch delivers SAP consulting, AI automation, enterprise software, and digital transformation services to help businesses scale faster.",
  },
  blog: {
    title: "Digital Transformation Blog | SAP, AI & SEO Insights",
    description:
      "Read expert blogs on SAP, AI, SEO, WhatsApp automation, enterprise software, digital marketing, and business transformation.",
  },
  services: {
    title: "Enterprise Technology Services | SAP, AI & Software",
    description:
      "Explore SAP consulting, AI automation, enterprise software, digital marketing, and custom technology services from SoftClinch.",
  },
  enterpriseSoftware: {
    title: "Enterprise Software Development Company | SoftClinch",
    description:
      "Build scalable enterprise software, ERP, CRM, SaaS platforms, and workflow automation solutions tailored to your business.",
  },
  about: {
    title: "About SoftClinch | SAP, AI & Technology Experts",
    description:
      "Learn about SoftClinch, a trusted technology consulting company delivering SAP, AI, software development, and digital transformation solutions.",
  },
  sapConsulting: {
    title: "SAP Consulting Services | SAP Implementation & Support",
    description:
      "Accelerate business growth with SAP consulting, S/4HANA implementation, migration, AMS, rollout, and support services.",
  },
  customApplicationDevelopment: {
    title: "Custom Application Development Company | SoftClinch",
    description:
      "Develop secure and scalable web, mobile, SaaS, and enterprise applications tailored to your business requirements.",
  },
  digitalMarketing: {
    title: "Digital Marketing Company | SEO, Google Ads & Growth",
    description:
      "Grow your business with SEO, Google Ads, performance marketing, lead generation, and conversion-focused digital marketing services.",
  },
  contact: {
    title: "Contact SoftClinch | Book a Free Consultation",
    description:
      "Contact SoftClinch for SAP consulting, AI automation, software development, digital marketing, and enterprise technology solutions.",
  },
  softClinchAi: {
    title: "AI Automation Company | AI Business Solutions",
    description:
      "Transform your business with AI automation, chatbots, intelligent workflows, generative AI, and enterprise AI solutions.",
  },
  inaiwazhiWhatsAppAutomation: {
    title: "WhatsApp Business API & Automation Platform",
    description:
      "Automate WhatsApp messaging with chatbots, broadcasts, CRM integration, campaigns, and AI-powered customer engagement.",
  },
  commerceEnablement: {
    title: "Ecommerce Development Company | Commerce Solutions",
    description:
      "Launch high-performing ecommerce websites with Shopify, WooCommerce, automation, SEO, and conversion optimization services.",
  },
  aiPoweredBusinessSystems: {
    title: "AI Business Automation & Workflow Solutions",
    description:
      "Streamline operations with AI-powered business systems, workflow automation, intelligent process automation, and enterprise AI.",
  },
  sapAmsSupport: {
    title: "SAP AMS Services | SAP Application Management Support",
    description:
      "Ensure business continuity with SAP AMS, technical support, functional support, maintenance, monitoring, and optimization services.",
  },
} as const;
